---

- name: "01.1 - make sure base play directory exists and world writable"
  file:
    path: "{{ __cni_play_dir }}"
    state: directory
    owner: 0
    group: 0
    mode: "a=rwX"
  become: yes

- name: "01.2 - make sure cni installation and config directories exist"
  file:
    path: "{{ item }}"
    state: directory
    mode: "ug=rwX,o-rwx"
  become: yes
  loop:
    - "{{ __cni_install_dir }}"
    - "{{ __cni_config_dir }}"
