---

- name: "03.1 - template cni bridge and loopback configs"
  template:
    src: "{{ item }}"
    dest: "{{ __cni_config_dir }}/{{ item }}"
  become: yes
  loop:
    - 10-bridge.conf
    - 99-loopback.conf
